server:
  error:
    include-message: always
    include-binding-errors: always
spring:
  datasource:
#    Winning Community
#    password: "purpbelieves"
#    url: "jdbc:mysql://mysql-winningcommunitee.alwaysdata.net/winningcommunitee_db?reconnect=true"
#    username: "294017"

#    Solid Payout
    password: "adrian10jet"
    url: "jdbc:mysql://mysql-solidpayout.alwaysdata.net/solidpayout_db?reconnect=true"
    username: "309217"
#    password:
#    url: "jdbc:mysql://localhost:3306/predictz_db?reconnect=true"
#    username: root

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
    show-sql: false