server:
  error:
    include-message: always
    include-binding-errors: always
spring:
  datasource:
    password:
    url: "jdbc:mysql://localhost:3306/predictz_db?reconnect=true"
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
    show-sql: false